export default defineNuxtConfig({
  modules: ['@vueuse/nuxt', '@nuxt/fonts', 'nuxt-og-image'],
  devtools: { enabled: true },
  compatibilityDate: '2026-06-16',
  site: {
    url: 'https://playrecuerdo.vercel.app',
    name: 'Recall',
  },
  // Panda CSS is generated by the CLI (`panda --watch` in dev, `panda` before
  // build) and imported as a static stylesheet. We deliberately do NOT use the
  // experimental @pandacss/dev/postcss plugin — in v2 beta it emitted corrupted
  // semantic-token values (e.g. `--colors-fg: var(--colors-paper) #FAFAFA`),
  // breaking the :root rule. See design-notes/v2-beta-dogfooding.md.
  css: ['~~/styled-system/styles.css'],
  fonts: {
    families: [
      { name: 'Archivo', provider: 'google', weights: [400, 700, 800, 900], global: true },
      { name: 'Geist Mono', provider: 'google', weights: [500, 600], global: true },
    ],
  },
  app: {
    head: {
      htmlAttrs: { lang: 'en' },
      title: 'Recall',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'description', content: 'How many numbers can you remember before time runs out?' },
        { name: 'theme-color', content: '#0a0a0a' },
      ],
    },
  },
  routeRules: {
    '/': { isr: 60 },
  },
  ogImage: {
    defaults: { renderer: 'takumi' },
  },
  vite: {
    optimizeDeps: {
      include: ['@ark-ui/vue/dialog', '@vueuse/core', '@vue/devtools-core', '@vue/devtools-kit'],
    },
  },
})
